"""Hard task: full warehouse optimization under disruptions."""

from __future__ import annotations

from env.models import SKUConfig, WarehouseConfig
from env.warehouse_env import WarehouseEnv


TASK_NAME = "full_warehouse_optimization"


HARD_SKUS = [
    SKUConfig(
        sku_id="SKU-201",
        name="Gaming Keyboard",
        unit_cost=48.0,
        holding_cost_rate=0.008,
        stockout_penalty=24.0,
        max_stock=110,
        reorder_point=52,
        supplier_lead_time_mean=5.0,
        supplier_lead_time_std=2.0,
        demand_mean=18.0,
        demand_std=5.5,
        seasonality_amplitude=0.16,
        seasonality_period=14,
        demand_trend=0.06,
    ),
    SKUConfig(
        sku_id="SKU-202",
        name="USB-C Hub",
        unit_cost=30.0,
        holding_cost_rate=0.007,
        stockout_penalty=20.0,
        max_stock=125,
        reorder_point=58,
        supplier_lead_time_mean=5.0,
        supplier_lead_time_std=2.0,
        demand_mean=22.0,
        demand_std=6.0,
        seasonality_amplitude=0.11,
        seasonality_period=7,
        demand_trend=0.05,
    ),
    SKUConfig(
        sku_id="SKU-203",
        name="Noise Cancelling Headset",
        unit_cost=85.0,
        holding_cost_rate=0.01,
        stockout_penalty=36.0,
        max_stock=90,
        reorder_point=42,
        supplier_lead_time_mean=5.0,
        supplier_lead_time_std=2.0,
        demand_mean=14.0,
        demand_std=4.0,
        seasonality_amplitude=0.19,
        seasonality_period=21,
        demand_trend=0.08,
    ),
    SKUConfig(
        sku_id="SKU-204",
        name="Webcam 4K",
        unit_cost=62.0,
        holding_cost_rate=0.009,
        stockout_penalty=32.0,
        max_stock=95,
        reorder_point=44,
        supplier_lead_time_mean=5.0,
        supplier_lead_time_std=2.0,
        demand_mean=13.0,
        demand_std=3.8,
        seasonality_amplitude=0.14,
        seasonality_period=14,
        demand_trend=0.04,
    ),
    SKUConfig(
        sku_id="SKU-205",
        name="External SSD",
        unit_cost=74.0,
        holding_cost_rate=0.009,
        stockout_penalty=34.0,
        max_stock=100,
        reorder_point=46,
        supplier_lead_time_mean=5.0,
        supplier_lead_time_std=2.0,
        demand_mean=15.0,
        demand_std=4.3,
        seasonality_amplitude=0.17,
        seasonality_period=30,
        demand_trend=0.07,
    ),
    SKUConfig(
        sku_id="SKU-206",
        name="Ergonomic Chair Mat",
        unit_cost=56.0,
        holding_cost_rate=0.006,
        stockout_penalty=22.0,
        max_stock=88,
        reorder_point=40,
        supplier_lead_time_mean=5.0,
        supplier_lead_time_std=2.0,
        demand_mean=10.0,
        demand_std=3.0,
        seasonality_amplitude=0.09,
        seasonality_period=14,
        demand_trend=0.03,
    ),
    SKUConfig(
        sku_id="SKU-207",
        name="LED Desk Lamp",
        unit_cost=28.0,
        holding_cost_rate=0.007,
        stockout_penalty=18.0,
        max_stock=120,
        reorder_point=54,
        supplier_lead_time_mean=5.0,
        supplier_lead_time_std=2.0,
        demand_mean=20.0,
        demand_std=5.2,
        seasonality_amplitude=0.12,
        seasonality_period=7,
        demand_trend=0.05,
    ),
    SKUConfig(
        sku_id="SKU-208",
        name="Smart Thermostat",
        unit_cost=96.0,
        holding_cost_rate=0.011,
        stockout_penalty=38.0,
        max_stock=80,
        reorder_point=36,
        supplier_lead_time_mean=5.0,
        supplier_lead_time_std=2.0,
        demand_mean=9.0,
        demand_std=2.8,
        seasonality_amplitude=0.2,
        seasonality_period=30,
        demand_trend=0.09,
    ),
    SKUConfig(
        sku_id="SKU-209",
        name="Power Strip",
        unit_cost=18.0,
        holding_cost_rate=0.005,
        stockout_penalty=14.0,
        max_stock=150,
        reorder_point=66,
        supplier_lead_time_mean=5.0,
        supplier_lead_time_std=2.0,
        demand_mean=30.0,
        demand_std=7.5,
        seasonality_amplitude=0.08,
        seasonality_period=7,
        demand_trend=0.04,
    ),
    SKUConfig(
        sku_id="SKU-210",
        name="Protective Mailer",
        unit_cost=4.5,
        holding_cost_rate=0.004,
        stockout_penalty=9.0,
        max_stock=230,
        reorder_point=100,
        supplier_lead_time_mean=5.0,
        supplier_lead_time_std=2.0,
        demand_mean=58.0,
        demand_std=10.0,
        seasonality_amplitude=0.06,
        seasonality_period=7,
        demand_trend=0.02,
    ),
]


def make_config() -> WarehouseConfig:
    """Build hard task configuration with disruptions and emergency supply."""
    return WarehouseConfig(
        num_skus=10,
        warehouse_capacity=680,
        max_episode_steps=60,
        task_difficulty="hard",
        stochastic_demand=True,
        stochastic_lead_times=True,
        skus=HARD_SKUS,
        reward_weights={"w1": 0.38, "w2": 0.16, "w3": 0.24, "w4": 0.1, "w5": 0.07, "w6": 0.05},
        discount_factor=0.97,
        emergency_supply_enabled=True,
        emergency_supply_cost_multiplier=2.8,
        disruption_probability=0.2,
    )


def make_env() -> WarehouseEnv:
    """Instantiate hard task environment."""
    return WarehouseEnv(make_config())
